// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type RegisterRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *RegisterRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type LogoutRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Close struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Close) Reset()         { *m = Close{} }
func (m *Close) String() string { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()    {}
func (*Close) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *Close) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Close.Unmarshal(m, b)
}
func (m *Close) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Close.Marshal(b, m, deterministic)
}
func (m *Close) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Close.Merge(m, src)
}
func (m *Close) XXX_Size() int {
	return xxx_messageInfo_Close.Size(m)
}
func (m *Close) XXX_DiscardUnknown() {
	xxx_messageInfo_Close.DiscardUnknown(m)
}

var xxx_messageInfo_Close proto.InternalMessageInfo

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePic           []byte   `protobuf:"bytes,3,opt,name=profile_pic,json=profilePic,proto3" json:"profile_pic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetProfilePic() []byte {
	if m != nil {
		return m.ProfilePic
	}
	return nil
}

type Message struct {
	SenderId             string   `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TargetId             string   `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Read                 bool     `protobuf:"varint,5,opt,name=read,proto3" json:"read,omitempty"`
	Media                *Media   `protobuf:"bytes,6,opt,name=media,proto3" json:"media,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *Message) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *Message) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Message) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Message) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *Message) GetMedia() *Media {
	if m != nil {
		return m.Media
	}
	return nil
}

type Media struct {
	// Types that are valid to be assigned to Data:
	//	*Media_ChunkSize
	//	*Media_Image
	//	*Media_Video
	//	*Media_File
	//	*Media_Empty
	Data                 isMedia_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (m *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(m, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

type isMedia_Data interface {
	isMedia_Data()
}

type Media_ChunkSize struct {
	ChunkSize int32 `protobuf:"varint,4,opt,name=chunkSize,proto3,oneof"`
}

type Media_Image struct {
	Image []byte `protobuf:"bytes,1,opt,name=image,proto3,oneof"`
}

type Media_Video struct {
	Video []byte `protobuf:"bytes,2,opt,name=video,proto3,oneof"`
}

type Media_File struct {
	File []byte `protobuf:"bytes,3,opt,name=file,proto3,oneof"`
}

type Media_Empty struct {
	Empty bool `protobuf:"varint,5,opt,name=empty,proto3,oneof"`
}

func (*Media_ChunkSize) isMedia_Data() {}

func (*Media_Image) isMedia_Data() {}

func (*Media_Video) isMedia_Data() {}

func (*Media_File) isMedia_Data() {}

func (*Media_Empty) isMedia_Data() {}

func (m *Media) GetData() isMedia_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Media) GetChunkSize() int32 {
	if x, ok := m.GetData().(*Media_ChunkSize); ok {
		return x.ChunkSize
	}
	return 0
}

func (m *Media) GetImage() []byte {
	if x, ok := m.GetData().(*Media_Image); ok {
		return x.Image
	}
	return nil
}

func (m *Media) GetVideo() []byte {
	if x, ok := m.GetData().(*Media_Video); ok {
		return x.Video
	}
	return nil
}

func (m *Media) GetFile() []byte {
	if x, ok := m.GetData().(*Media_File); ok {
		return x.File
	}
	return nil
}

func (m *Media) GetEmpty() bool {
	if x, ok := m.GetData().(*Media_Empty); ok {
		return x.Empty
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Media) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Media_ChunkSize)(nil),
		(*Media_Image)(nil),
		(*Media_Video)(nil),
		(*Media_File)(nil),
		(*Media_Empty)(nil),
	}
}

type MediaResponse struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaResponse) Reset()         { *m = MediaResponse{} }
func (m *MediaResponse) String() string { return proto.CompactTextString(m) }
func (*MediaResponse) ProtoMessage()    {}
func (*MediaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *MediaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaResponse.Unmarshal(m, b)
}
func (m *MediaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaResponse.Marshal(b, m, deterministic)
}
func (m *MediaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaResponse.Merge(m, src)
}
func (m *MediaResponse) XXX_Size() int {
	return xxx_messageInfo_MediaResponse.Size(m)
}
func (m *MediaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MediaResponse proto.InternalMessageInfo

func (m *MediaResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *MediaResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SignupRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignupResponse struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *SignupResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AddFriendRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendRequest) Reset()         { *m = AddFriendRequest{} }
func (m *AddFriendRequest) String() string { return proto.CompactTextString(m) }
func (*AddFriendRequest) ProtoMessage()    {}
func (*AddFriendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *AddFriendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendRequest.Unmarshal(m, b)
}
func (m *AddFriendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendRequest.Marshal(b, m, deterministic)
}
func (m *AddFriendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendRequest.Merge(m, src)
}
func (m *AddFriendRequest) XXX_Size() int {
	return xxx_messageInfo_AddFriendRequest.Size(m)
}
func (m *AddFriendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendRequest proto.InternalMessageInfo

func (m *AddFriendRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AddFriendResponse struct {
	Done                 bool     `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFriendResponse) Reset()         { *m = AddFriendResponse{} }
func (m *AddFriendResponse) String() string { return proto.CompactTextString(m) }
func (*AddFriendResponse) ProtoMessage()    {}
func (*AddFriendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *AddFriendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFriendResponse.Unmarshal(m, b)
}
func (m *AddFriendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFriendResponse.Marshal(b, m, deterministic)
}
func (m *AddFriendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFriendResponse.Merge(m, src)
}
func (m *AddFriendResponse) XXX_Size() int {
	return xxx_messageInfo_AddFriendResponse.Size(m)
}
func (m *AddFriendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFriendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFriendResponse proto.InternalMessageInfo

func (m *AddFriendResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *AddFriendResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AddFriendResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*LogoutRequest)(nil), "proto.LogoutRequest")
	proto.RegisterType((*Close)(nil), "proto.Close")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*Media)(nil), "proto.Media")
	proto.RegisterType((*MediaResponse)(nil), "proto.MediaResponse")
	proto.RegisterType((*SignupRequest)(nil), "proto.SignupRequest")
	proto.RegisterType((*SignupResponse)(nil), "proto.SignupResponse")
	proto.RegisterType((*AddFriendRequest)(nil), "proto.AddFriendRequest")
	proto.RegisterType((*AddFriendResponse)(nil), "proto.AddFriendResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x51, 0x6b, 0x13, 0x41,
	0x10, 0xee, 0xa5, 0xb9, 0x34, 0x37, 0x49, 0x6a, 0x5d, 0x62, 0x3d, 0xa2, 0xd8, 0xb2, 0x4f, 0x01,
	0xa1, 0x94, 0x4a, 0x45, 0x5f, 0x04, 0x15, 0xa5, 0x55, 0x0b, 0xb2, 0xc5, 0x17, 0x5f, 0xca, 0x36,
	0x3b, 0x9e, 0x8b, 0xbd, 0xdb, 0x73, 0x77, 0x53, 0xa8, 0xff, 0xc1, 0xff, 0xe0, 0x1f, 0xf0, 0x3f,
	0xca, 0xce, 0x6e, 0x5a, 0x1b, 0x69, 0xf1, 0x29, 0x3b, 0xdf, 0xcc, 0x7c, 0xdf, 0xcc, 0xe4, 0x3b,
	0x18, 0x39, 0xb4, 0xe7, 0x7a, 0x86, 0x3b, 0xad, 0x35, 0xde, 0xb0, 0x9c, 0x7e, 0xf8, 0x1a, 0xe4,
	0x6f, 0xea, 0xd6, 0x5f, 0xf0, 0x77, 0x70, 0x47, 0x60, 0xa5, 0x9d, 0x47, 0x2b, 0xf0, 0xfb, 0x1c,
	0x9d, 0x67, 0x5b, 0xd0, 0x9d, 0x3b, 0xb4, 0x65, 0xb6, 0x9d, 0x4d, 0x07, 0x7b, 0x83, 0xd8, 0xb8,
	0xf3, 0xc9, 0xa1, 0x15, 0x94, 0x60, 0x9b, 0xd0, 0x93, 0x33, 0xaf, 0xcf, 0xb1, 0xec, 0x6c, 0x67,
	0xd3, 0xbe, 0x48, 0x11, 0xdf, 0x82, 0xd1, 0x07, 0x53, 0x99, 0xb9, 0x5f, 0x30, 0xad, 0x43, 0x47,
	0x2b, 0xe2, 0x29, 0x44, 0x47, 0xab, 0xa0, 0xfa, 0xfa, 0xcc, 0x38, 0xe4, 0xef, 0xa1, 0x1b, 0xf8,
	0x96, 0x0b, 0x18, 0x83, 0x6e, 0x23, 0xeb, 0xc8, 0x5b, 0x08, 0x7a, 0xb3, 0x2d, 0x18, 0xb4, 0xd6,
	0x7c, 0xd1, 0x67, 0x78, 0xd2, 0xea, 0x59, 0xb9, 0xba, 0x9d, 0x4d, 0x87, 0x02, 0x12, 0xf4, 0x51,
	0xcf, 0xf8, 0xef, 0x0c, 0xd6, 0x8e, 0xd0, 0x39, 0x59, 0x21, 0x7b, 0x00, 0x85, 0xc3, 0x46, 0xa1,
	0x3d, 0xb9, 0xe4, 0xed, 0x47, 0xe0, 0x50, 0x85, 0xa4, 0x97, 0xb6, 0x42, 0x1f, 0x92, 0x51, 0xa2,
	0x1f, 0x81, 0x43, 0x92, 0x3e, 0x35, 0xea, 0x82, 0xf8, 0x0b, 0x41, 0x6f, 0xf6, 0x10, 0x0a, 0xaf,
	0x6b, 0x74, 0x5e, 0xd6, 0x6d, 0xd9, 0xa5, 0xc4, 0x15, 0x10, 0x3a, 0x2c, 0x4a, 0x55, 0xe6, 0x74,
	0x04, 0x7a, 0x33, 0x0e, 0x79, 0x8d, 0x4a, 0xcb, 0xb2, 0x47, 0xc7, 0x1b, 0xa6, 0xe3, 0x1d, 0x05,
	0x4c, 0xc4, 0x14, 0xff, 0x99, 0x41, 0x4e, 0x00, 0x7b, 0x04, 0xc5, 0xec, 0xeb, 0xbc, 0xf9, 0x76,
	0xac, 0x7f, 0x20, 0xf1, 0xe7, 0x07, 0x2b, 0xe2, 0x0a, 0x62, 0x9b, 0x90, 0xeb, 0x5a, 0x56, 0x48,
	0x9b, 0x0c, 0x0f, 0x56, 0x44, 0x0c, 0x03, 0x7e, 0xae, 0x15, 0x1a, 0x5a, 0x82, 0x70, 0x0a, 0xd9,
	0x18, 0xba, 0xe1, 0x28, 0xf1, 0x46, 0x07, 0x2b, 0x82, 0xa2, 0x50, 0x8d, 0xe1, 0xbf, 0x8e, 0x83,
	0x86, 0x6a, 0x0a, 0x5f, 0xf5, 0xa0, 0xab, 0xa4, 0x97, 0xfc, 0x39, 0x8c, 0xe2, 0x7c, 0xe8, 0x5a,
	0xd3, 0x38, 0x0c, 0x8b, 0x29, 0xd3, 0x44, 0xd5, 0xbe, 0xa0, 0x37, 0x1b, 0x43, 0x8e, 0xd6, 0x1a,
	0x9b, 0xee, 0x16, 0x03, 0xbe, 0x0b, 0xa3, 0x63, 0x5d, 0x35, 0xf3, 0xf6, 0x7f, 0xbd, 0xc3, 0x9f,
	0xc2, 0xfa, 0xa2, 0xe3, 0x16, 0xb5, 0x0d, 0x58, 0xad, 0x5d, 0x95, 0xb4, 0xc2, 0x93, 0x73, 0xd8,
	0x78, 0xa9, 0xd4, 0x5b, 0xab, 0xb1, 0x51, 0x37, 0xd9, 0xeb, 0x33, 0xdc, 0xfd, 0xab, 0xe6, 0x16,
	0xfa, 0xc5, 0x94, 0x9d, 0x9b, 0x1c, 0x9e, 0xf4, 0x57, 0x2f, 0xf5, 0xf7, 0x7e, 0x75, 0xa0, 0x08,
	0x26, 0xd3, 0x4d, 0x85, 0x96, 0xed, 0x43, 0xcf, 0xd1, 0x16, 0x6c, 0x9c, 0x9a, 0xaf, 0x9d, 0x61,
	0x72, 0x6f, 0x09, 0x4d, 0xb3, 0xbc, 0x80, 0x42, 0x2e, 0x06, 0x64, 0xf7, 0x53, 0xcd, 0xf2, 0x5a,
	0x93, 0xf2, 0xdf, 0x44, 0xea, 0x7f, 0x0c, 0x83, 0x60, 0xe6, 0x85, 0xd9, 0xd7, 0x2f, 0xdd, 0x45,
	0xf1, 0x64, 0xe1, 0x36, 0xfa, 0xc6, 0xd8, 0x33, 0x18, 0xce, 0x2c, 0x4a, 0x8f, 0xc7, 0xde, 0xa2,
	0xac, 0xd9, 0x66, 0xca, 0x2e, 0x7d, 0xee, 0x93, 0x25, 0x96, 0xdd, 0x8c, 0xed, 0xc3, 0x60, 0xde,
	0x9e, 0x19, 0xa9, 0xa2, 0x4b, 0x97, 0x65, 0xc6, 0xd7, 0x4c, 0x9d, 0x66, 0x9b, 0x66, 0xa7, 0x3d,
	0x82, 0x9f, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xd9, 0x8a, 0x31, 0x72, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MessingerClient is the client API for Messinger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessingerClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Close, error)
	CreateStream(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (Messinger_CreateStreamClient, error)
	UploadMedia(ctx context.Context, opts ...grpc.CallOption) (Messinger_UploadMediaClient, error)
}

type messingerClient struct {
	cc *grpc.ClientConn
}

func NewMessingerClient(cc *grpc.ClientConn) MessingerClient {
	return &messingerClient{cc}
}

func (c *messingerClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/proto.Messinger/signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messingerClient) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	out := new(AddFriendResponse)
	err := c.cc.Invoke(ctx, "/proto.Messinger/addFriend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messingerClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Close, error) {
	out := new(Close)
	err := c.cc.Invoke(ctx, "/proto.Messinger/sendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messingerClient) CreateStream(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (Messinger_CreateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messinger_serviceDesc.Streams[0], "/proto.Messinger/createStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &messingerCreateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Messinger_CreateStreamClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type messingerCreateStreamClient struct {
	grpc.ClientStream
}

func (x *messingerCreateStreamClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messingerClient) UploadMedia(ctx context.Context, opts ...grpc.CallOption) (Messinger_UploadMediaClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Messinger_serviceDesc.Streams[1], "/proto.Messinger/uploadMedia", opts...)
	if err != nil {
		return nil, err
	}
	x := &messingerUploadMediaClient{stream}
	return x, nil
}

type Messinger_UploadMediaClient interface {
	Send(*Message) error
	CloseAndRecv() (*MediaResponse, error)
	grpc.ClientStream
}

type messingerUploadMediaClient struct {
	grpc.ClientStream
}

func (x *messingerUploadMediaClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messingerUploadMediaClient) CloseAndRecv() (*MediaResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MediaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessingerServer is the server API for Messinger service.
type MessingerServer interface {
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	AddFriend(context.Context, *AddFriendRequest) (*AddFriendResponse, error)
	SendMessage(context.Context, *Message) (*Close, error)
	CreateStream(*RegisterRequest, Messinger_CreateStreamServer) error
	UploadMedia(Messinger_UploadMediaServer) error
}

// UnimplementedMessingerServer can be embedded to have forward compatible implementations.
type UnimplementedMessingerServer struct {
}

func (*UnimplementedMessingerServer) Signup(ctx context.Context, req *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedMessingerServer) AddFriend(ctx context.Context, req *AddFriendRequest) (*AddFriendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFriend not implemented")
}
func (*UnimplementedMessingerServer) SendMessage(ctx context.Context, req *Message) (*Close, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedMessingerServer) CreateStream(req *RegisterRequest, srv Messinger_CreateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateStream not implemented")
}
func (*UnimplementedMessingerServer) UploadMedia(srv Messinger_UploadMediaServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadMedia not implemented")
}

func RegisterMessingerServer(s *grpc.Server, srv MessingerServer) {
	s.RegisterService(&_Messinger_serviceDesc, srv)
}

func _Messinger_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessingerServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Messinger/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessingerServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messinger_AddFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessingerServer).AddFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Messinger/AddFriend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessingerServer).AddFriend(ctx, req.(*AddFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messinger_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessingerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Messinger/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessingerServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messinger_CreateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessingerServer).CreateStream(m, &messingerCreateStreamServer{stream})
}

type Messinger_CreateStreamServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type messingerCreateStreamServer struct {
	grpc.ServerStream
}

func (x *messingerCreateStreamServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Messinger_UploadMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessingerServer).UploadMedia(&messingerUploadMediaServer{stream})
}

type Messinger_UploadMediaServer interface {
	SendAndClose(*MediaResponse) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type messingerUploadMediaServer struct {
	grpc.ServerStream
}

func (x *messingerUploadMediaServer) SendAndClose(m *MediaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messingerUploadMediaServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Messinger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Messinger",
	HandlerType: (*MessingerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "signup",
			Handler:    _Messinger_Signup_Handler,
		},
		{
			MethodName: "addFriend",
			Handler:    _Messinger_AddFriend_Handler,
		},
		{
			MethodName: "sendMessage",
			Handler:    _Messinger_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "createStream",
			Handler:       _Messinger_CreateStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "uploadMedia",
			Handler:       _Messinger_UploadMedia_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
